export const initialKnowledge = {
    a: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    b: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    c: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    d: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    e: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    f: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    g: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    h: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    i: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    j: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    k: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    l: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    m: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    n: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    o: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    p: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    q: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    r: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    s: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    t: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    u: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    v: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    w: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    x: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    y: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
    z: {confirmedPos: [], confirmedPresence: false, possPos: [0, 1, 2, 3, 4]},
}